/*
 * HomePanel.java
 *
 * 
 */

package se.wsu.lmw.LMS.view.home;

import se.wsu.lmw.LMS.view.home.Home;
import se.wsu.lmw.LMS.view.search.Search_By_Publisher1;
import se.wsu.lmw.LMS.view.search.Search_By_AuthorNameID1;
import se.wsu.lmw.LMS.view.search.Search_BookNameID1;
import se.wsu.lmw.LMS.view.Register.Register_New_Member1;
import se.wsu.lmw.LMS.view.Register.Register_New_Librian;
import se.wsu.lmw.LMS.view.Register.Register_New_Book1;
import se.wsu.lmw.Controls.Date.Date1;
import se.wsu.lmw.Controls.PanelLoad1;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import se.wsu.lmw.Controls.Report;
import se.wsu.lmw.LMS.BookReturn1;
import se.wsu.lmw.LMS.IaasuABook1;
import se.wsu.lmw.LMS.Librian_Details1;
import se.wsu.lmw.LMS.Member_Details1;
import se.wsu.lmw.LMS.Settings1;
import se.wsu.lmw.LMS.User_Privilages;

/**
 *
 * @author Imashi
 */
public class HomePanel extends javax.swing.JPanel {

    String lid;
    String librian;

    Register_New_Member1 rnm;
    Register_New_Book1 rnb;
    Register_New_Librian rnl;
    Search_BookNameID1 sbnid;
    Search_By_AuthorNameID1 sba;
    IaasuABook1 isue;
    Search_By_Publisher1 sbp;
    BookReturn1 br;
    Librian_Details1 sel;
    Member_Details1 md;
//Settings settings;

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
    }
    //constructor overload

    public HomePanel(String librianName, String LID) {
        librian = librianName;
        lid = LID;
        initComponents();
        if (librian.contains("_Guest")) {
            jLabel6.setText("Guest Name :");
        }

        lblLibrian_on_Duty.setText(librian);
        lblLibrian_ID.setText(LID);
        //---------date---------------        
        jLabel10.setText(Date1.myDate());
        //----------------------------
        
        jLabel1.setForeground(Color.BLACK);
        jLabel2.setForeground(Color.BLACK);
        jLabel3.setForeground(Color.BLACK);
        jLabel4.setForeground(Color.BLACK);
        jLabel12.setForeground(Color.BLACK);
        jLabel13.setForeground(Color.BLACK);
        jLabel14.setForeground(Color.BLACK);
        jLabel5.setForeground(Color.BLACK);
        jLabel7.setForeground(Color.BLACK);
        jLabel15.setForeground(Color.BLACK);
        jLabel18.setForeground(Color.BLACK);
        jLabel19.setForeground(Color.BLACK);
        jLabel14.setVisible(false);
        jTaskPaneGroup6_Profile.setVisible(false);
        jTaskPaneGroup3.setVisible(false);
        if (lblLibrian_on_Duty.getText().contains("Admin")) {

            jLabel14.setVisible(true);
            jTaskPaneGroup6_Profile.setVisible(true);
        } else if (lblLibrian_on_Duty.getText().contains("Guest")) {
            jTaskPaneGroup2.setVisible(false);
            jTaskPaneGroup3.setVisible(false);
            jTaskPaneGroup4.setVisible(false);
            
            jTaskPaneGroup6_Profile.setVisible(false);
        }
        new Thread(new Runnable() {

            public void run() {
                while (true) {
                    Date d = new Date();

                    String date = d.toString();
                    String arr1[] = date.split(" ");
                    jLabel20.setText(arr1[3]);
                    try {
                        Thread.sleep(1000);
                        System.gc();
                    } catch (InterruptedException ex) {
                        System.out.println("Home time thread err");
                    }

                }
            }
        }).start();
        jLabel21.setVisible(false);
        jLabel25.setVisible(false);
        jLabel26.setVisible(false);
        jLabel27.setVisible(false);
        jLabel28.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblLibrian_on_Duty = new javax.swing.JLabel();
        lblLibrian_ID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTaskPane1 = new com.l2fprod.common.swing.JTaskPane();
        jTaskPaneGroup1 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTaskPaneGroup2 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTaskPaneGroup3 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLabel5 = new javax.swing.JLabel();
        jTaskPaneGroup4 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTaskPaneGroup6_Profile = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTaskPaneGroup5 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("Librarian on Duty :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 180, 30));

        lblLibrian_on_Duty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLibrian_on_Duty.setForeground(new java.awt.Color(204, 255, 204));
        lblLibrian_on_Duty.setText("jLabel5");
        jPanel1.add(lblLibrian_on_Duty, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 190, 30));

        lblLibrian_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLibrian_ID.setForeground(new java.awt.Color(204, 255, 204));
        lblLibrian_ID.setText("jLabel7");
        jPanel1.add(lblLibrian_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 660, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 660, 70, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("jLabel9");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 660, 170, 30));

        jLabel11.setBackground(new java.awt.Color(204, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Time :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 660, 70, 30));

        jLabel20.setBackground(new java.awt.Color(204, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 255, 255));
        jLabel20.setText("jLabel11");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, 110, 30));

        jPanel3.setOpaque(false);
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wow1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 790, 530));

        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel29MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 80));

        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 70));

        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 90, 80));

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 90, 80));

        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 100, 70));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User Privilages.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 90));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Settingsssss.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 0, 130, 90));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Main Window.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
        });
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 0, -1, 90));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel27MouseExited(evt);
            }
        });
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 120, 90));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AboutUSs.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel26MouseExited(evt);
            }
        });
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 90));

        jPanel2.setOpaque(false);

        jTaskPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTaskPane1MouseEntered(evt);
            }
        });

        jTaskPaneGroup1.setTitle("Search Book Details");
        jTaskPaneGroup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTaskPaneGroup1MouseEntered(evt);
            }
        });

        jLabel2.setText("With Book Name/Book ID");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jTaskPaneGroup1.getContentPane().add(jLabel2);

        jLabel3.setText("With Author Name/ author ID");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jTaskPaneGroup1.getContentPane().add(jLabel3);

        jLabel4.setText("With Publisher Name/ ID");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jTaskPaneGroup1.getContentPane().add(jLabel4);

        jTaskPane1.add(jTaskPaneGroup1);

        jTaskPaneGroup2.setTitle("Register");

        jLabel12.setText("Register New Members");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jTaskPaneGroup2.getContentPane().add(jLabel12);

        jLabel13.setText("Register New Books");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jTaskPaneGroup2.getContentPane().add(jLabel13);

        jLabel14.setText("Register New Librarian");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jTaskPaneGroup2.getContentPane().add(jLabel14);

        jTaskPane1.add(jTaskPaneGroup2);

        jTaskPaneGroup3.setTitle("Remove");

        jLabel5.setText("Remove Librarian Details");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jTaskPaneGroup3.getContentPane().add(jLabel5);

        jTaskPane1.add(jTaskPaneGroup3);

        jTaskPaneGroup4.setTitle("Activity");

        jLabel7.setText("Issue a Book");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jTaskPaneGroup4.getContentPane().add(jLabel7);

        jLabel15.setText("Return a Book");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jTaskPaneGroup4.getContentPane().add(jLabel15);

        jTaskPane1.add(jTaskPaneGroup4);

        jTaskPaneGroup6_Profile.setTitle("Profile");

        jLabel18.setText("Search / Edit Librarian Details");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        jTaskPaneGroup6_Profile.getContentPane().add(jLabel18);

        jLabel19.setText("Search / Edit Member Details");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        jTaskPaneGroup6_Profile.getContentPane().add(jLabel19);

        jTaskPane1.add(jTaskPaneGroup6_Profile);

        jTaskPaneGroup5.setTitle("Reports");

        jLabel16.setText("Print Book List");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        jTaskPaneGroup5.getContentPane().add(jLabel16);

        jLabel17.setText("Print Borrowed Book List");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        jTaskPaneGroup5.getContentPane().add(jLabel17);

        jTaskPane1.add(jTaskPaneGroup5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTaskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTaskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/normalBackground2 copy.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            // TODO add your handling code here:
            sbnid = new Search_BookNameID1();
        } catch (SQLException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    PanelLoad1.LoadPanel(sbnid, HomePanel.jPanel3);
    System.gc();

}//GEN-LAST:event_jLabel2MouseClicked

private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
// TODO add your handling code here:

    jLabel2.setForeground(Color.DARK_GRAY);
    System.gc();
}//GEN-LAST:event_jLabel2MouseEntered

private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
// TODO add your handling code here:
    jLabel2.setForeground(Color.BLACK);
    System.gc();
}//GEN-LAST:event_jLabel2MouseExited

private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
// TODO add your handling code here:
    sba = new Search_By_AuthorNameID1();
    PanelLoad1.LoadPanel(sba, HomePanel.jPanel3);

}//GEN-LAST:event_jLabel3MouseClicked

private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
// TODO add your handling code here:
    jLabel3.setForeground(Color.DARK_GRAY);
    System.gc();
}//GEN-LAST:event_jLabel3MouseEntered

private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
// TODO add your handling code here:
    jLabel3.setForeground(Color.BLACK);
    System.gc();
}//GEN-LAST:event_jLabel3MouseExited

private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
// TODO add your handling code here:
    sbp = new Search_By_Publisher1();
    PanelLoad1.LoadPanel(sbp, HomePanel.jPanel3);
}//GEN-LAST:event_jLabel4MouseClicked

private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
// TODO add your handling code here:
    jLabel4.setForeground(Color.DARK_GRAY);
    System.gc();
}//GEN-LAST:event_jLabel4MouseEntered

private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
// TODO add your handling code here:
    jLabel4.setForeground(Color.BLACK);
    System.gc();
}//GEN-LAST:event_jLabel4MouseExited

private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
    rnm = new Register_New_Member1(librian, lid);
    PanelLoad1.LoadPanel(rnm, HomePanel.jPanel3);
}//GEN-LAST:event_jLabel12MouseClicked

private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
// TODO add your handling code here:
    jLabel12.setForeground(Color.DARK_GRAY);
}//GEN-LAST:event_jLabel12MouseEntered

private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
// TODO add your handling code here:
    jLabel12.setForeground(Color.BLACK);
    System.gc();
}//GEN-LAST:event_jLabel12MouseExited

private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
// TODO add your handling code here:
    rnb = new Register_New_Book1(librian, lid);
    PanelLoad1.LoadPanel(rnb, HomePanel.jPanel3);

}//GEN-LAST:event_jLabel13MouseClicked

private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
// TODO add your handling code here:
    jLabel13.setForeground(Color.DARK_GRAY);
    System.gc();
}//GEN-LAST:event_jLabel13MouseEntered

private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
// TODO add your handling code here:
    jLabel13.setForeground(Color.BLACK);
    System.gc();
}//GEN-LAST:event_jLabel13MouseExited

private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
    rnl = new Register_New_Librian(librian, lid);
    PanelLoad1.LoadPanel(rnl, HomePanel.jPanel3);
}//GEN-LAST:event_jLabel14MouseClicked

private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
// TODO add your handling code here:
    jLabel14.setForeground(Color.DARK_GRAY);
    System.gc();
}//GEN-LAST:event_jLabel14MouseEntered

private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
// TODO add your handling code here:
    jLabel14.setForeground(Color.BLACK);
    System.gc();
}//GEN-LAST:event_jLabel14MouseExited

private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
// TODO add your handling code here:
    jLabel5.setForeground(Color.DARK_GRAY);
    System.gc();
}//GEN-LAST:event_jLabel5MouseEntered

private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
// TODO add your handling code here:
    jLabel5.setForeground(Color.BLACK);
    System.gc();
}//GEN-LAST:event_jLabel5MouseExited

private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
// TODO add your handling code here:
    isue = new IaasuABook1(librian, lid);
    PanelLoad1.LoadPanel(isue, HomePanel.jPanel3);

}//GEN-LAST:event_jLabel7MouseClicked

private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
// TODO add your handling code here:
    jLabel7.setForeground(Color.DARK_GRAY);
    System.gc();
}//GEN-LAST:event_jLabel7MouseEntered

private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
// TODO add your handling code here:
    jLabel7.setForeground(Color.BLACK);
    System.gc();
}//GEN-LAST:event_jLabel7MouseExited

private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
    br = new BookReturn1(librian, lid);
    PanelLoad1.LoadPanel(br, HomePanel.jPanel3);

}//GEN-LAST:event_jLabel15MouseClicked

private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
// TODO add your handling code here:
    jLabel15.setForeground(Color.DARK_GRAY);
    System.gc();
}//GEN-LAST:event_jLabel15MouseEntered

private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
// TODO add your handling code here:
    jLabel15.setForeground(Color.BLACK);
    System.gc();
}//GEN-LAST:event_jLabel15MouseExited

private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
    sel = new Librian_Details1(librian, lid);
    PanelLoad1.LoadPanel(sel, HomePanel.jPanel3);

}//GEN-LAST:event_jLabel18MouseClicked

private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
    jLabel18.setForeground(Color.DARK_GRAY);
    System.gc();
}//GEN-LAST:event_jLabel18MouseEntered

private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
    jLabel18.setForeground(Color.BLACK);
    System.gc();
}//GEN-LAST:event_jLabel18MouseExited

private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
    md = new Member_Details1();
    PanelLoad1.LoadPanel(md, HomePanel.jPanel3);

}//GEN-LAST:event_jLabel19MouseClicked

private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
    jLabel19.setForeground(Color.DARK_GRAY);
    System.gc();
}//GEN-LAST:event_jLabel19MouseEntered

private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
    jLabel19.setForeground(Color.BLACK);
    System.gc();
}//GEN-LAST:event_jLabel19MouseExited

private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
    User_Privilages up = new User_Privilages(librian, lid);
    PanelLoad1.LoadPanel(up, Home.jPanel2);
}//GEN-LAST:event_jLabel21MouseClicked

private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
    jLabel21.setVisible(false);
}//GEN-LAST:event_jLabel21MouseExited

private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    Hp1 hp1 = new Hp1(librian, lid);
    PanelLoad1.LoadPanel(hp1, Home.jPanel2);

}//GEN-LAST:event_jLabel8MouseClicked

private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
    jLabel27.setVisible(true);
    jLabel26.setVisible(false);

    jLabel21.setVisible(false);
    jLabel28.setVisible(false);
    jLabel25.setVisible(false);
}//GEN-LAST:event_jLabel8MouseEntered

private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited

}//GEN-LAST:event_jLabel8MouseExited

private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
    jLabel26.setVisible(true);
    jLabel21.setVisible(false);
    jLabel25.setVisible(false);
    jLabel27.setVisible(false);
    jLabel28.setVisible(false);
}//GEN-LAST:event_jLabel22MouseEntered

private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited

}//GEN-LAST:event_jLabel22MouseExited

private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
    HomePanel hp1 = new HomePanel(librian, lid);
    PanelLoad1.LoadPanel(hp1, Home.jPanel2);
}//GEN-LAST:event_jLabel23MouseClicked

private void jLabel23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseEntered
    jLabel28.setVisible(true);
    jLabel21.setVisible(false);
    jLabel25.setVisible(false);
    jLabel26.setVisible(false);
    jLabel27.setVisible(false);
}//GEN-LAST:event_jLabel23MouseEntered

private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
    jLabel28.setVisible(false);
}//GEN-LAST:event_jLabel23MouseExited

private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
    if (lblLibrian_on_Duty.getText().contains("Admin") == true) {
        Settings1 S = new Settings1(librian, lid);
        PanelLoad1.LoadPanel(S, Home.jPanel2);
    } else {
        JOptionPane.showMessageDialog(null, "You Don't Have Permission To view Settings");
    }
}//GEN-LAST:event_jLabel24MouseClicked

private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
    jLabel25.setVisible(true);
    jLabel26.setVisible(false);
    jLabel27.setVisible(false);
    jLabel28.setVisible(false);

    jLabel21.setVisible(false);
}//GEN-LAST:event_jLabel24MouseEntered

private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered

}//GEN-LAST:event_jLabel25MouseEntered

private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
    jLabel25.setVisible(false);
}//GEN-LAST:event_jLabel25MouseExited

private void jLabel26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseExited
    jLabel26.setVisible(false);
}//GEN-LAST:event_jLabel26MouseExited

private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
    Hp1 hp1 = new Hp1(librian, lid);
    PanelLoad1.LoadPanel(hp1, Home.jPanel2);
}//GEN-LAST:event_jLabel27MouseClicked

private void jLabel27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseExited
    jLabel27.setVisible(false);
}//GEN-LAST:event_jLabel27MouseExited

private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
    jLabel28.setVisible(false);
}//GEN-LAST:event_jLabel28MouseExited

private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
    User_Privilages up = new User_Privilages(librian, lid);
    PanelLoad1.LoadPanel(up, Home.jPanel2);
}//GEN-LAST:event_jLabel29MouseClicked

private void jLabel29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseEntered
    jLabel21.setVisible(true);
    jLabel25.setVisible(false);
    jLabel26.setVisible(false);
    jLabel27.setVisible(false);
    jLabel28.setVisible(false);
}//GEN-LAST:event_jLabel29MouseEntered

private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
    jLabel21.setVisible(false);
    jLabel25.setVisible(false);
    jLabel26.setVisible(false);
    jLabel27.setVisible(false);
    jLabel28.setVisible(false);
}//GEN-LAST:event_jLabel1MouseEntered

private void jTaskPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaskPane1MouseEntered
    jLabel21.setVisible(false);
    jLabel25.setVisible(false);
    jLabel26.setVisible(false);
    jLabel27.setVisible(false);
    jLabel28.setVisible(false);
}//GEN-LAST:event_jTaskPane1MouseEntered

private void jTaskPaneGroup1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaskPaneGroup1MouseEntered
    jLabel21.setVisible(false);
    jLabel25.setVisible(false);
    jLabel26.setVisible(false);
    jLabel27.setVisible(false);
    jLabel28.setVisible(false);
}//GEN-LAST:event_jTaskPaneGroup1MouseEntered

private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
    jLabel21.setVisible(false);
    jLabel25.setVisible(false);
    jLabel26.setVisible(false);
    jLabel27.setVisible(false);
    jLabel28.setVisible(false);
}//GEN-LAST:event_jPanel3MouseEntered

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        
        new Report().Create_report();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        jLabel16.setForeground(Color.DARK_GRAY);
        System.gc();
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        jLabel16.setForeground(Color.BLACK);
        System.gc();
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        new Report().Create_report2();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        jLabel17.setForeground(Color.DARK_GRAY);
        System.gc();
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        jLabel17.setForeground(Color.BLACK);
        System.gc();
    }//GEN-LAST:event_jLabel17MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    private com.l2fprod.common.swing.JTaskPane jTaskPane1;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup1;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup2;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup3;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup4;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup5;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup6_Profile;
    private javax.swing.JLabel lblLibrian_ID;
    private javax.swing.JLabel lblLibrian_on_Duty;
    // End of variables declaration//GEN-END:variables

}
