/*
 * Home.java
 *
 * 
 */
package se.wsu.lmw.LMS.view.home;

import se.wsu.lmw.Controls.PanelLoad1;
import java.awt.AWTException;
import java.awt.Frame;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;

/**
 *
 * @author Imashi
 */
public class Home extends javax.swing.JFrame {

    String Lib_Name;
    String LID;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();

    }

    //constructor overload
    public Home(String librian, String LibID) {
        
        //setting frame location and image.
        initComponents();
        int x = (int) ((Toolkit.getDefaultToolkit().getScreenSize().getWidth() - getWidth()) / 2);
        int y = (int) ((Toolkit.getDefaultToolkit().getScreenSize().getHeight() - getHeight()) / 2);
        setLocation(x, y);

        Lib_Name = librian;
        LID = LibID;
        Hp1 hp = new Hp1(Lib_Name, LID);
        PanelLoad1.LoadPanel(hp, Home.jPanel2);
        TrayIcon trayIcon;

        SystemTray trau = SystemTray.getSystemTray();

        Image image = Toolkit.getDefaultToolkit().getImage("LMSpng.png");

        trayIcon = new TrayIcon(image, "Easy Way 1.1 LMS ");
        trayIcon.setImageAutoSize(true);

        try {
            trau.add(trayIcon);

        } catch (AWTException ex) {

        }
        trayIcon.displayMessage("Easy Way LMS 1.1 ", "Welcome To Easy Way Library Management System 1.1 \n Easy Way LMS 1.1 just Active the Features You need Making your Experience quicker and cleaner", TrayIcon.MessageType.INFO);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyWay 1.1 Library Management System");
        setResizable(false);

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
